name: Build, Push to NCP, and Deploy

on:
  push:
    branches:
      - 7-feat-git-actions

jobs:
  build-and-push-to-ncp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean install

      - name: Log in to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: vst.kr.ncr.ntruss.com
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            vst.kr.ncr.ntruss.com/vst/my-app:latest
            vst.kr.ncr.ntruss.com/vst/my-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ncp
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Login to NCP Container Registry..."
            echo "${{ secrets.NCP_SECRET_KEY }}" | docker login --username ${{ secrets.NCP_ACCESS_KEY }} --password-stdin vst.kr.ncr.ntruss.com
            
            echo "Pulling latest Docker image..."
            docker pull vst.kr.ncr.ntruss.com/vst/my-app:latest
            
            echo "Stopping old container..."
            docker stop my-app || true
            docker rm my-app || true
            
            echo "Starting new container..."
            docker run -d -p 8080:8080 --name my-app vst.kr.ncr.ntruss.com/vst/api-server:latest
